version: '3.8'

services:
  # 1. 데이터베이스 (PostGIS 포함)
  db:
    image: postgis/postgis:13-3.1
    container_name: gis-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  # 본인이 쓸 비번으로 바꾸세요!
      - POSTGRES_DB=gisgraduation_version2
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # 2. 지오서버
  geoserver:
    image: kartoza/geoserver
    container_name: gis-geoserver
    environment:
      - GEOSERVER_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"  # 노트북에서는 8081 포트로 접속하게 설정
    volumes:
      - ./geoserver-data:/opt/geoserver/data_dir
    depends_on:
      - db

  # 3. 내 백엔드 (방금 만든 이미지 사용)
  backend:
    image: gis-backend
    container_name: gis-backend
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gisgraduation_version2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres # 위 DB 랑 비번 똑같이 하기