DROP TABLE IF EXISTS minbangwi;

CREATE TABLE minbangwi (
    gid TEXT,
    "2" TEXT,
    manage_number TEXT,
    "2009-12-15" TEXT,
    "unnamed_ 3" TEXT,
    "사용중" TEXT,
    dedong_semugo TEXT,
    sisul_gubum TEXT,
    detail_address TEXT,
    address_number TEXT,
    "03057" TEXT,
    underground TEXT,
    max_area TEXT,
    max_depi_person TEXT,
    "2025-11-20" TEXT,
    u TEXT,
    "2025-11-22" TEXT,
    "37" TEXT,
    "34" TEXT,
    "51.8" TEXT,
    "126" TEXT,
    "59" TEXT,
    "14.94" TEXT,
    "37.5810562" TEXT,
    "126.987482" TEXT,
    longitude TEXT,
    latitude TEXT,
    city_code TEXT,
    city_number TEXT,
    city TEXT,
    henjung_code TEXT,
    henjung_name TEXT,
    geom TEXT
);